Update return-to-claim.njk
hmcts/et-sya-frontend pull request #1670
Opened 2024-09-02 14:41 UTC by cindychmcts

### JIRA link

https://tools.hmcts.net/jira/browse/RET-5385

### Change description

Remove "| safe" from return-to-existing

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2024-09-02 15:38 UTC, hsjhita approved these changes

2024-09-03 10:53 UTC, GauravChawlaMOJ requested changes
Can you please add unit test for this?

2024-09-03 13:01 UTC, hsjhita approved these changes

2024-09-03 13:35 UTC, GauravChawlaMOJ approved these changes

2024-09-04 14:40 UTC, merged