Ret 1975
hmcts/et-sya-frontend pull request #309
Opened 2022-08-15 15:05 UTC by DarylBoam

### JIRA link
https://tools.hmcts.net/jira/browse/RET-1975

### Change description
Changes to address details views to match figma design

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2022-08-15 16:01 UTC, marcjudge approved these changes

2022-08-15 16:03 UTC, lvo700 submitted a review, later dismissed

2022-08-15 16:03 UTC, brendanmchugh requested changes

2022-08-15 16:03 UTC, brendanmchugh commented on src/main/views/address/postcodeEnter.njk
> +    <div class="govuk-grid-row">
There is a CSS class for grouping two buttons together, side by side - "govuk-button-group" - should improve the alignment.

2022-08-16 08:47 UTC, brendanmchugh approved these changes

2022-08-19 09:29 UTC, lvo700 approved these changes

2022-08-19 10:41 UTC, marcjudge approved these changes

2022-08-19 13:26 UTC, merged