Ret 2195 employment details final checks
hmcts/et-sya-frontend pull request #312
Opened 2022-08-16 12:18 UTC by olyode

### JIRA link
https://tools.hmcts.net/jira/browse/RET-2195
### Change description
Final checks
Added label to average weekly hours input field
updated unit test
Updated average weekly hours hint text
**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-08-16 13:14 UTC, Itay-Kirsh requested changes

2022-08-16 13:14 UTC, Itay-Kirsh commented on src/main/resources/locales/en/translation/notice-length-weeks.json
> +      "notANumber": "Number of weeks in notice period must be a number, like 4 etc"
Dot after etc

2022-08-16 13:37 UTC, olyode commented on src/main/resources/locales/en/translation/notice-length-weeks.json
> +      "notANumber": "Number of weeks in notice period must be a number, like 4 etc"
Thanks @Itay-Kirsh . Done

2022-08-16 14:52 UTC, marcjudge commented on src/main/resources/locales/en/translation/notice-length-weeks.json
> +      "notANumber": "Number of weeks in notice period must be a number, like 4 etc"
Still missing the full stop here

2022-08-18 08:45 UTC, brendanmchugh approved these changes

2022-08-18 08:46 UTC, Itay-Kirsh approved these changes

2022-08-23 08:42 UTC, merged