Ret 2256 - add api call to front end
hmcts/et-sya-frontend pull request #324
Opened 2022-08-30 14:43 UTC by DarylBoam

### JIRA link
https://tools.hmcts.net/jira/browse/RET-2256

### Change description
Front end changes to make api call to et-sya-api document upload controller

**Does this PR introduce a breaking change?** (check one with "x")

```
[X] Yes
[ ] No
```

2022-09-01 08:13 UTC, marcjudge requested changes

2022-09-01 08:13 UTC, marcjudge commented on src/main/controllers/DescribeWhatHappenedController.ts
> +    await handleUploadDocument(req, req.body.claimSummaryFile, this.logger);
Could you please set the response from the call to the claimSummaryFile property on the userCase

2022-09-01 15:07 UTC, marcjudge submitted a review, later dismissed

2022-09-02 10:34 UTC, brendanmchugh approved these changes

2022-09-15 13:31 UTC, ikirsanov approved these changes

2022-09-15 13:52 UTC, marcjudge approved these changes

2022-09-15 14:25 UTC, merged