Ret 2673
hmcts/et-sya-frontend pull request #408
Opened 2022-10-13 16:27 UTC by robin-ieong

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x ] No
```

2022-10-13 16:31 UTC, marcjudge approved these changes

2022-10-13 16:40 UTC, fergusoshea approved these changes

2022-10-14 08:06 UTC, ikirsanov approved these changes

2022-10-14 09:05 UTC, marcjudge submitted a review, later dismissed

2022-10-14 09:07 UTC, lvo700 approved these changes

2022-10-17 11:24 UTC, JackReevies requested changes

2022-10-17 11:24 UTC, JackReevies commented on src/main/routes/routes.ts
> +    fileSize: 314572800,
Magic Number, could refactor this into a const with a good name (like LIMIT_300MB). This is referenced in two places

2022-10-17 11:24 UTC, JackReevies commented on src/main/routes/routes.ts
> +    if (fileSize > 314572800) {
the second place its referenced

2022-10-17 11:41 UTC, JackReevies approved these changes

2022-10-17 12:02 UTC, JackReevies approved these changes

2022-10-17 13:06 UTC, merged