Add logging
hmcts/et-sya-frontend pull request #419
Opened 2022-10-14 15:20 UTC by marcjudge

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link

### Change description

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2022-10-14 15:47 UTC, ikirsanov submitted a review, later dismissed

2022-10-17 08:08 UTC, gauravhmcts approved these changes

2022-10-17 08:11 UTC, JackReevies requested changes

2022-10-17 08:11 UTC, JackReevies commented on src/main/routes/routes.ts
> +  app.get(PageUrls.GET_SUMITTED_CASE_DOCUMENT, app.locals.container.cradle.submittedCaseDocumentController.get);
SUBMITTED?

2022-10-17 08:11 UTC, JackReevies commented on src/main/definitions/constants.ts
> +  GET_SUMITTED_CASE_DOCUMENT: '/getSubmittedCaseDocument/:docId',
SUBMITTED?

2022-10-17 08:13 UTC, marcjudge commented on src/main/routes/routes.ts
> +  app.get(PageUrls.GET_SUMITTED_CASE_DOCUMENT, app.locals.container.cradle.submittedCaseDocumentController.get);
Fixed

2022-10-17 08:13 UTC, marcjudge commented on src/main/definitions/constants.ts
> +  GET_SUMITTED_CASE_DOCUMENT: '/getSubmittedCaseDocument/:docId',
Fixed

2022-10-17 08:18 UTC, JackReevies approved these changes

2022-10-17 08:35 UTC, Itay-Kirsh approved these changes
We should definitely come back to this and try and figure out why a shared document controller didn't work. It's unfortunate to have two separate ones but it's probably best to get this through for now.

2022-10-17 08:35 UTC, merged