Ret 800
hmcts/et-sya-frontend pull request #57
Opened 2022-02-01 12:03 UTC by MatthewDalbyV1

[### JIRA link ###](https://tools.hmcts.net/jira/browse/RET-800)

added a button to return to claim which redirects you to login so you can continue with your existing claim

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2022-02-04 11:56 UTC, brendanmchugh requested changes
Does this page display okay on preview? I think there might be some imports missing in the nunjucks file.

2022-02-04 11:56 UTC, brendanmchugh commented on src/main/views/claim-saved.njk
> +        text: continueWithClaim,#
Is the # a typo?

2022-02-04 11:56 UTC, brendanmchugh commented on src/main/resources/locales/en/translation/claim-saved.json
> +    "continueWithClaim": "Continue with your claim"
The 'Continue with your claim' could be moved into the json translation file also.

2022-02-08 07:23 UTC, pmumbere commented on src/main/views/claim-saved.njk
> +        href: "/return-to-existing"
missing trailing comma

2022-02-08 07:24 UTC, pmumbere commented on src/main/views/claim-saved.njk
> +      })
missing closing double braces

2022-02-08 07:31 UTC, pmumbere commented on src/main/views/claim-saved.njk
> +        text: continueWithClaim,
missing claim-saved.json translation file. You added continueWithClaim entry to home.json but do not reference home.json in the YourClaimHasBeenSavedController controller. I think you need to create translation file claim-saved.json and move the continueWithClaim field to it.

2022-02-08 07:33 UTC, pmumbere requested changes
Please address the missing trailing braces and comma issue. Also please introduce translation file corresponding to what is passed for rendering in your controller. Also from the mock-up on the JIRA ticket I can see you are missing a paragraph with content

2022-02-09 14:31 UTC, pmumbere approved these changes

2022-02-09 16:47 UTC, brendanmchugh approved these changes

2022-02-22 09:38 UTC, merged