RET-2616-fix
hmcts/et-sya-frontend pull request #646
Opened 2023-02-01 14:27 UTC by ikirsanov

### JIRA link
https://tools.hmcts.net/jira/browse/RET-2616

### Change description
Bug fixes: 
     Contact the tribunal selected page fixes: 
               - Change the fontsize in njk
               - typo in translations
               - cancel link redirect to citizen hub                   

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x ] No
```

2023-02-01 14:29 UTC, marcjudge requested changes

2023-02-01 14:29 UTC, marcjudge commented on src/main/controllers/ContactTheTribunalSelectedController.ts
> +      'witness' === userCase.contactApplicationType ? PageUrls.CONTACT_THE_TRIBUNAL_CYA : PageUrls.COPY_TO_OTHER_PARTY;
Use a constant for this string

2023-02-01 14:31 UTC, paul-peasegood submitted a review, later dismissed

2023-02-01 14:42 UTC, ikirsanov commented on src/main/controllers/ContactTheTribunalSelectedController.ts
> +      'witness' === userCase.contactApplicationType ? PageUrls.CONTACT_THE_TRIBUNAL_CYA : PageUrls.COPY_TO_OTHER_PARTY;
Done

2023-02-01 16:07 UTC, marcjudge submitted a review, later dismissed

2023-02-01 16:24 UTC, marcjudge commented on src/main/definitions/constants.ts
> +  WITNESS: 'witness',
Lets rename this as TypeC

2023-02-02 08:30 UTC, ikirsanov commented on src/main/definitions/constants.ts
> +  WITNESS: 'witness',
Done

2023-02-02 09:08 UTC, marcjudge approved these changes

2023-02-02 11:37 UTC, Itay-Kirsh approved these changes

2023-02-02 11:50 UTC, merged